import { useState } from "react";

const useMode=(length:number)=>{
    return useState([...Array(length)].map(()=>Symbol("generated by useMode")))[0];
}

export {useMode as __________DEPRECATED_USE_MODE__________};